### ISSUE TITLE
The library is no longer accessable

### ISSUE THREAD

**Issue by MostHated** [Spencer-Easton/Apps-Script-htmlparser2-library#2]
Hey there,
 I realize I am several years late, but I came across this repo from StackOverflow and went to add the library, but unfortunately it comes back with an error saying:

```bash
The selected version of the library with identifier htmlparser2 is missing. (Perhaps it was deleted.) Please select a new version or remove this library.
```
Thanks,
-MH

**Comment by mblais** [comment]
@MostHated, the source is right here so you don't actually need the library. Just add the source to your project.

**Comment by MostHated** [comment]
Yeah, I was able to get it figured out a few months ago. Thanks.
